site_name: OpenMLDB docs
plugins:
  - search:

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 中文
      link: /zh/
      lang: zh

theme:
    name: material
    logo: zh/about/images/openmldb_logo.png
    favicon: zh/about/images/openmldb_favicon.png
    features:
      - navigation.tabs
      - navigation.top
      - navigation.indexes
